### ISSUE TITLE
[에러] swagger 사용자관리 - 회원가입 실패 에러

### ISSUE THREAD

**Issue by hwanfront** [KitTeamSe/se_api_server#118]
에러 발생 조건 : swagger 에서 [사용자관리] - [회원가입] 시 실패 및 잘못된 에러 메시지가 발생
api/v1/signup
Request : 
```
{
  "answer": "구미",
  "email": "abc@def.com",
  "id": "sturtust",
  "name": "name",
  "nickname": "nickname",
  "password": "se75407540",
  "phoneNumber": "01012345678",
  "questionId": 1,
  "studentId": 20150292,
  "type": "STUDENT"
}
```
![image](https://user-images.githubusercontent.com/65995108/114527841-63909280-9c83-11eb-8516-a939acfaa800.png)
외에 다른 Request도 똑같은 결과가 발생함.

픽스 후 조건 : 회원가입 실패 시 `존재하지 않는 사용자` 의 표현도 모호한 것 같고, 회원가입이 원활하게 완료되거나 조건의 기술이 필요함

**Comment by junhodo** [comment]
DB 문제인걸로 분석됨.
