### ISSUE TITLE
[기능] CORS 설정 추가

### ISSUE THREAD

**Issue by hwanfront** [KitTeamSe/se_api_server#123]
요청 기능 : FE에서 api 호출 시 CORS 뜨는 문제 해결
![image](https://user-images.githubusercontent.com/65995108/114709041-10900b80-9d67-11eb-9196-7ac0a92a3a3e.png)

**Comment by dldhk97** [comment]
CORS URL 변경

**Comment by dldhk97** [comment]
CORS 예외에 localhost 추가 필요
