### ISSUE TITLE
[에러] 메뉴 전체 조회 및  메뉴 정보 조회 출력 오류

### ISSUE THREAD

**Issue by jihun1233** [KitTeamSe/se_api_server#140]
에러 발생 조건 : (6하원칙)
- 폴더 메뉴 하위에 메뉴를 생성한 후 메뉴 전체 조회시 child 값이 비어서 나옴.
![image](https://user-images.githubusercontent.com/56039591/115103739-3861b800-9f8f-11eb-8b21-c6d1e2ff4d50.png)

- 메뉴 정보 조회 (id로 조회) 시 메시지가 성공적으로 삭제되었다고 나옴
![image](https://user-images.githubusercontent.com/56039591/115103797-98585e80-9f8f-11eb-9ee1-d5e62b141fb1.png)

픽스 후 조건 :
- 메뉴 전체 조회시 하위 메뉴인 child가 함께 출력
- 메뉴 정보 조회시 "성공적으로 조회되었습니다"로 메시지 출력

**Comment by junhodo** [comment]
resolved by c95100e
