### ISSUE TITLE
[기능] 게시글 전체 목록 조회

### ISSUE THREAD

**Issue by ChangXXX** [KitTeamSe/se_api_server#155]
요청 기능 :
해당 게시판 게시글 전체 목록 조회 기능 없습니다.
게시글 당 제목, 내용 앞부분, 작성 시간, 작성자, 댓글 수 아마 요정도 필요할 것 같습니다.

**Comment by dldhk97** [comment]
확인이 늦은 점 양해해주시기 바랍니다.

Swagger에서 게시글 관리 - 게시글 조회에서 특정 게시판의 게시글을 조회할 수 있습니다.
모든 게시글을 조회하는 기능은 없으며, 게시글 수가 많아지게 되면 전체 조회 비용이 너무 커지므로, 페이징으로 구현하였습니다.
게시판의 ID와, 정렬(오름차순,내림차순), 페이지 번호, 페이징 크기를 입력해주시면 그에 맞는 게시글 목록이 반환됩니다.

![image](https://user-images.githubusercontent.com/20237869/116988081-d7660e00-ad0a-11eb-9d4a-e13af63c1378.png)

응답은 위와 같이 이루어지며, 각 게시글에 대한 제목, 게시글 ID, 조회 수, 작성시간, 댓글 수 등의 정보가 반환됩니다.
작성자와 내용 앞부분을 함께 반환할지에 대해서는 팀 내에서 상의해봐야 할 것으로 보입니다.

게시글 추가를 위해서는 게시판 추가가 필요한데, 현재 게시판 추가가 오류로 인해 정상적으로 수행되지 않습니다.
#158 에서 해당 이슈를 해결하였기 때문에
추후 코드 리뷰 후 병합이 되면 Live Swagger에 반영될 예정입니다.

**Comment by dldhk97** [comment]
응답 시 작성자의 닉네임과 내용 앞부분 20자를 함께 반환하도록 하겠습니다.

**Comment by dldhk97** [comment]
추가적인 변경 사항이 없다면 이슈 닫도록 하겠습니다.
