### ISSUE TITLE
[기능] 게시글(Post) 삭제 시 파일 서버에 삭제 요청 필요

### ISSUE THREAD

**Issue by dldhk97** [KitTeamSe/se_api_server#172]
요청 기능 : 게시글(Post) 삭제 시 파일 서버에 삭제 요청 필요
현재 첨부파일이 존재하는 게시글 삭제 시 API DB에서는 첨부파일이 삭제가 이루어지지만
파일 서버에 존재한는 실제 파일은 삭제되지 않음.
게시글 삭제 시 파일 서버에 파일 삭제 요청을 하여야 함.

**Comment by junhodo** [comment]
로직 변경으로 인해 삭제
