### ISSUE TITLE
[기능] 게시판에 따른 게시글 목록 조회 응답에 태그정보 추가

### ISSUE THREAD

**Issue by jihun1233** [KitTeamSe/se_api_server#177]
요청 기능 :
![image](https://user-images.githubusercontent.com/56039591/118470956-2caa1280-b742-11eb-9c96-6e3f4ae629f1.png)
현재 각 게시글마다 태그정보가 없음. 태그정보도 함께 받을 수 있도록 추가 요청

**Comment by jihun1233** [comment]
!추가 
게시판의 이름도 함께 받을 수 있으면 좋겠음 - 게시판 제목 표시

**Comment by dldhk97** [comment]
게시글 목록 조회 시 태그 목록이 함께 반환되도록 수정하였습니다. (#179)
게시판의 이름을 받는 것은 현재 [메뉴 관리] - [메뉴 전체 조회] 를 통해 메뉴 ID와 메뉴 이름을 조회할 수 있지만,
위 요청에 대하여 BE팀 내에서 의견을 나눠보고 다시 응답드리겠습니다.

**Comment by dldhk97** [comment]
@junhodo 
위 요청에서 게시글 목록 조회 시 게시판의 이름도 함께 반환되기를 희망합니다.

**Comment by dldhk97** [comment]
Resolved at #243.
