### ISSUE TITLE
[기능] SuccessResponse  수정

### ISSUE THREAD

**Issue by junhodo** [KitTeamSe/se_api_server#196]
요청 기능 :
String code 생성
int code -> int status로 변경

**Comment by dldhk97** [comment]
### ErrorCode, SuccessResponse 변수 통일화
1. 기존에는 ErrorCode와 SuccessResponse의 변수 이름 및 타입이 반대로 되어있어서 혼동이 되었었음(아래 그림 참고)
![image](https://user-images.githubusercontent.com/20237869/119368649-3d342d00-bcee-11eb-84ba-0c8f7bc487b9.png)
이를 통일하기 위해 상대적으로 수정할 곳이 적은 SuccessResponse의 int code를 int status로 변경하려 했으나,
Swagger에서 표시되는 Code(int)와 혼동될 우려가 있다고 판단하였음.

2. ErrorCode의 변수명 및 타입을 변경하여 통일화
![image](https://user-images.githubusercontent.com/20237869/119370150-edeefc00-bcef-11eb-85b4-07f117ad29d1.png)
code 변수에는 int형으로, HTTP Code를 저장하게끔 하였고,
status 변수에는 식별자를 저장하는 것으로 통일하였음.

3. 결론
- SuccessResponse에 status 변수 추가(Default 값으로 SR01, 필요한 경우 생성자로 할당 가능)
- ErrorCode에는 int status를 int code로, String code를 String status로 변경하였음.

**Comment by dldhk97** [comment]
Resolved at #197.
