### ISSUE TITLE
[에러] 회원 정보 조회 데이터가 넘어오지 않는 에러

### ISSUE THREAD

**Issue by hwanfront** [KitTeamSe/se_api_server#210]
에러 발생 조건 : 관리자가 회원 정보 조회 요청 시 data가 넘어오지 않음
픽스 후 조건 : 정상적으로 조회 데이터가 넘어와야 함
![image](https://user-images.githubusercontent.com/65995108/119778825-eb182500-bf02-11eb-9ce2-4e80dd470625.png)
![image](https://user-images.githubusercontent.com/65995108/119779088-3cc0af80-bf03-11eb-8df6-ee4ad15e2b27.png)

**Comment by dldhk97** [comment]
Resolved at #211.
